# Generated by Django 5.0.6 on 2024-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='temp_media_urls',
            field=models.JSONField(default=list),
        ),
    ]
