# Generated by Django 5.0.6 on 2024-09-20 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_client_temp_media_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 20, 19, 17, 9, 871117, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
